// Code generated by protoc-gen-go.
// source: hola.proto
// DO NOT EDIT!

/*
Package grpcutil is a generated protocol buffer package.

It is generated from these files:
	hola.proto

It has these top-level messages:
	HolaRequest
	HolaResponse
*/
package grpcutil

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HolaRequest struct {
}

func (m *HolaRequest) Reset()                    { *m = HolaRequest{} }
func (m *HolaRequest) String() string            { return proto.CompactTextString(m) }
func (*HolaRequest) ProtoMessage()               {}
func (*HolaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HolaResponse struct {
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *HolaResponse) Reset()                    { *m = HolaResponse{} }
func (m *HolaResponse) String() string            { return proto.CompactTextString(m) }
func (*HolaResponse) ProtoMessage()               {}
func (*HolaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HolaResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*HolaRequest)(nil), "grpcutil.HolaRequest")
	proto.RegisterType((*HolaResponse)(nil), "grpcutil.HolaResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Test service

type TestClient interface {
	Hola(ctx context.Context, in *HolaRequest, opts ...grpc.CallOption) (*HolaResponse, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) Hola(ctx context.Context, in *HolaRequest, opts ...grpc.CallOption) (*HolaResponse, error) {
	out := new(HolaResponse)
	err := grpc.Invoke(ctx, "/grpcutil.Test/Hola", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Test service

type TestServer interface {
	Hola(context.Context, *HolaRequest) (*HolaResponse, error)
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_Hola_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HolaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Hola(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcutil.Test/Hola",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Hola(ctx, req.(*HolaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcutil.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hola",
			Handler:    _Test_Hola_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hola.proto",
}

func init() { proto.RegisterFile("hola.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xc8, 0xcf, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2f, 0x2a, 0x48, 0x2e, 0x2d, 0xc9, 0xcc,
	0x91, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb,
	0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xa8, 0x53, 0xe2, 0xe5, 0xe2, 0xf6, 0xc8,
	0xcf, 0x49, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0xd2, 0xe2, 0xe2, 0x81, 0x70, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xa4, 0xb8, 0x38, 0xd2, 0x8b, 0x52, 0x53, 0x4b, 0x32, 0xf3,
	0xd2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x23, 0x1f, 0x2e, 0x96, 0x90, 0xd4,
	0xe2, 0x12, 0x21, 0x17, 0x2e, 0x16, 0x90, 0x1e, 0x21, 0x51, 0x3d, 0x98, 0x9d, 0x7a, 0x48, 0x46,
	0x4a, 0x89, 0xa1, 0x0b, 0x43, 0x8c, 0x56, 0xe2, 0x6d, 0xba, 0xfc, 0x64, 0x32, 0x13, 0xbb, 0x10,
	0xab, 0x3e, 0xc8, 0xd9, 0x49, 0x6c, 0x60, 0xf7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x22,
	0x08, 0x2e, 0xb9, 0xc5, 0x00, 0x00, 0x00,
}
